const responses1 = {
    1: 'Официальный Discord сервера Phoenix [01]: https://discord.gg/arizona-phoenix',
    2: 'Официальный Discord сервера Tucson [02]: https://discord.gg/tucson',
    3: 'Официальный Discord сервера Scottdale [03]: https://discord.gg/WVNBNUnHpr',
    4: 'Официальный Discord сервера Chandler [04]: https://discord.gg/d7cJKa9',
    5: 'Официальный Discord сервера Brainburg [05]: https://discord.gg/brainburg',
    6: 'Официальный Discord сервера Saint-Rose [06]: https://discord.gg/saintrose',
    7: 'Официальный Discord сервера Mesa [07]: https://discord.gg/ZCJx7T5e',
    8: 'Официальный Discord сервера Red-Rock [08]: https://discord.gg/kp7ENmW',
    9: 'Официальный Discord сервера Yuma [09]: https://discord.gg/29Ac9vxFvS',
    10: 'Официальный Discord сервера Surprise [10]: https://discord.gg/tRtNkVq',
    11: 'Официальный Discord сервера Prescott [11]: https://discord.gg/3yawqzxG7d',
    12: 'Официальный Discord сервера Glendale [12]: https://discord.gg/nQaznGz',
    13: 'Официальный Discord сервера Kingman [13]: https://discord.gg/kDVyX2K',
    14: 'Официальный Discord сервера Winslow [14]: https://discord.gg/winslow',
    15: 'Официальный Discord сервера Payson [15]: https://discord.gg/HwHxxVkxBc',
    16: 'Официальный Discord сервера Gilbert [16]: https://discord.gg/HrXsMHNUf4',
    17: 'Официальный Discord сервера Show-Low [17]: https://discord.gg/arz17',
    18: 'Официальный Discord сервера Casa-Grande [18]: https://discord.gg/yBW4MSYjNP',
    19: 'Официальный Discord сервера Page [19]: https://discord.gg/WzbNWcKQnr',
    20: 'Официальный Discord сервера Sun-City [20]: https://discord.gg/JA6FubbMad',
    21: 'Официальный Discord сервера Queen-Creek [21]: https://discord.gg/5ME9YRjP4t',
    22: 'Официальный Discord сервера Sedona [22]: https://discord.gg/sedona',
    23: 'Официальный Discord сервера Holiday [23]: https://discord.gg/aZSrYkW9DU',
    24: 'Официальный Discord сервера Wednesday [24]: https://discord.gg/arzwd',
    25: 'Официальный Discord сервера Yava [25]: https://discord.gg/yava',
    26: 'Официальный Discord сервера Faraway [26]: https://discord.gg/2J7Cq28uXB',
    27: 'Официальный Discord сервера Bumble Bee [27]: https://discord.gg/FfxYH5ZHX5',
    28: 'Официальный Discord сервера Christmas [28]: https://discord.gg/arzchristmas',
    29: 'Официальный Discord сервера Mirage [29]: https://discord.gg/4n2ZT4DTVt',
    30: 'Официальный Discord сервера Love [30]: https://discord.com/invite/T4kH3b6DxP',
};

const responses2 = {
    1: 'Раздел на форуме сервера Phoenix [01]: https://forum.arizona-rp.com/forums/338/',
    2: 'Раздел на форуме сервера Tucson [02]: https://forum.arizona-rp.com/forums/339/',
    3: 'Раздел на форуме сервера Scottdale [03]: https://forum.arizona-rp.com/forums/340/',
    4: 'Раздел на форуме сервера Chandler [04]: https://forum.arizona-rp.com/forums/352/',
    5: 'Раздел на форуме сервера Brainburg [05]: https://forum.arizona-rp.com/forums/539/',
    6: 'Раздел на форуме сервера Saint-Rose [06]: https://forum.arizona-rp.com/forums/681/',
    7: 'Раздел на форуме сервера Mesa [07]: https://forum.arizona-rp.com/forums/753/',
    8: 'Раздел на форуме сервера Red-Rock [08]: https://forum.arizona-rp.com/forums/837/',
    9: 'Раздел на форуме сервера Yuma [09]: https://forum.arizona-rp.com/forums/953/',
    10: 'Раздел на форуме сервера Surprise [10]: https://forum.arizona-rp.com/forums/1053/',
    11: 'Раздел на форуме сервера Prescott [11]: https://forum.arizona-rp.com/forums/1132/',
    12: 'Раздел на форуме сервера Glendale [12]: https://forum.arizona-rp.com/forums/1232/',
    13: 'Раздел на форуме сервера Kingman [13]: https://forum.arizona-rp.com/forums/1290/',
    14: 'Раздел на форуме сервера Winslow [14]: https://forum.arizona-rp.com/forums/1397/',
    15: 'Раздел на форуме сервера Payson [15]: https://forum.arizona-rp.com/forums/1469/',
    16: 'Раздел на форуме сервера Gilbert [16]: https://forum.arizona-rp.com/forums/1583/',
    17: 'Раздел на форуме сервера Show-Low [17]: https://forum.arizona-rp.com/forums/1685/',
    18: 'Раздел на форуме сервера Casa-Grande [18]: https://forum.arizona-rp.com/forums/1779/',
    19: 'Раздел на форуме сервера Page [19]: https://forum.arizona-rp.com/forums/1907/',
    20: 'Раздел на форуме сервера Sun-City [20]: https://forum.arizona-rp.com/forums/1986/',
    21: 'Раздел на форуме сервера Queen-Creek [21]: https://forum.arizona-rp.com/forums/2134/',
    22: 'Раздел на форуме сервера Sedona [22]: https://forum.arizona-rp.com/forums/2298/',
    23: 'Раздел на форуме сервера Holiday [23]: https://forum.arizona-rp.com/forums/2467/',
    24: 'Раздел на форуме сервера Wednesday [24]: https://forum.arizona-rp.com/forums/2557/',
    25: 'Раздел на форуме сервера Yava [25]: https://forum.arizona-rp.com/forums/2756/',
    26: 'Раздел на форуме сервера Faraway [26]: https://forum.arizona-rp.com/forums/2905/',
    27: 'Раздел на форуме сервера Bumble Bee [27]: https://forum.arizona-rp.com/forums/3005/',
    28: 'Раздел на форуме сервера Christmas [28]: https://forum.arizona-rp.com/forums/3093/',
    29: 'Раздел на форуме сервера Mirage [29]: https://forum.arizona-rp.com/forums/3206/',
    30: 'Раздел на форуме сервера Love [30]: https://forum.arizona-rp.com/forums/3289/',
};

module.exports = {responses1, responses2};